### PR TITLE
Bump version to use 

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**
We might need lerna to manage multiple package? @octref What's your opinion?

### CODE REVIEW

**Comment by octref** [comment]
I see I'm too used to the old way of publishing it 😅

**Comment by octref** [comment]
I'll publish 0.3 for vue-language-server then.

**Comment by HerringtonDarkholme** [comment]
@octref  I have already published vue-language-server.

One thing I notice is after installing vetur from vscode store. `server` directory still presents in the extension. But `server` has been listed in `.vscodeignore`, any idea?

**Comment by octref** [comment]
I don't think VSCode excludes it. There is an update to `vsce` (tool for publishing) I'll try it.

**Comment by octref** [comment]
I never had experience with lerna though. But with #254 we are almost having 3 packages with their own deps and package.json so it might be worth it.

Lerna seems pretty useful and I'm not against it at all.

**Comment by octref** [comment]
And think it needs to be `server/**/*` instead of `server`.

**Pull request merged**
